Blog/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new_post, name='new_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
]

accounts/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models

# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    """Sign up user."""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            # Login user with the username/pw
            login(request, authenticated_user)
            # Redirect to home page
            return HttpResponseRedirect(reverse('blogs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

blogs/views.py
from django.shortcuts import render
from .models import BlogPost
from django.shortcuts import render, redirect
from .forms import BlogPostForm
from django.shortcuts import get_object_or_404
# Create your views here.

def index(request):
    posts = BlogPost.objects.order_by('-date_added')
    context = {'posts':posts}
    return render(request, 'blogs/index.html', context)

def new_post(request):
    if request.method !='POST':
        form = BlogPostForm()
    else:
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

def edit_post(request, post_id):
    post = get_object_or_404(BlogPost, id=post_id)
    if request.method !='POST':
        form =BlogPostForm(instance=post)
    else:
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')
    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)
        

blogs/templates/blogs/edit_post.html
<h2>Edit message</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save edit</button>
</form>  

blogs/templates/blogs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Домашняя страница</title>
</head>
<body>
    <h1>Blog</h1>
    <a href="{% url 'blogs:new_post' %}">Создать новое сообщение</a>
    <ul>
        {% for post in posts %}
            <li>
                <strong>{{ post.title }}</strong> ({{ post.date_added }}):<br>
                {{ post.text }}<br>
                <a href="{% url 'blogs:edit_post' post.id %}">Редактировать</a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

blogs/templates/blogs/new_post.html
<h2>New message</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>